tasks:
  - command: pip install -U platformio && pip install --upgrade pip && platformio run -t clean -e tasmota32

image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - shardulm94.trailing-spaces
